package org.processmining.padsutils.plugins.inout;

import org.processmining.contexts.uitopia.annotations.UIExportPlugin;
import org.processmining.framework.plugin.PluginContext;
import org.processmining.framework.plugin.annotations.Plugin;
import org.processmining.framework.plugin.annotations.PluginVariant;
import org.processmining.padsutils.inout.EpExport;
import org.processmining.models.episode_leemans.EpisodeModel;
import org.processmining.plugins.episode_leemans.EpisodeMinerPlugin;

import java.io.IOException;
import java.io.File;

@Plugin(
    name = "Export Episodes as Text",
    returnLabels = {},
    returnTypes = {},
    parameterLabels = {"EpisodeModel", "File"},
    userAccessible = true
)
@UIExportPlugin(
    description = "Export Episodes generated by Leemans Episode Miner package as plain Text.",
    extension = "txt"
)
public class EpisodeModelExportPlugin {

    @PluginVariant(requiredParameterLabels = {0,1})
    public void export(PluginContext context, EpisodeModel model, File file) throws IOException {
        EpExport.exportEpisodes(model, file);
    }
}