package org.processmining.padsutils.plugins.inout;

import org.processmining.contexts.uitopia.annotations.UIExportPlugin;
import org.processmining.framework.plugin.PluginContext;
import org.processmining.framework.plugin.annotations.Plugin;
import org.processmining.framework.plugin.annotations.PluginVariant;
import org.processmining.lpm.util.LocalProcessModelRanking;
import org.processmining.padsutils.inout.LPMsExport;

import java.io.File;
import java.io.IOException;

@Plugin(
        name = "Export local process models as Petri nets",
        returnLabels = {},
        returnTypes = {},
        parameterLabels = {"LocalProcessModelRanking", "File"})
@UIExportPlugin(
        description = "Export local process models generated by LocalProcessModelDiscovery package as Petri nets in a zip.",
        extension = "zip")
public class TaxLPMsExportPlugin {

    @PluginVariant(variantLabel = "Export local process models into a file", requiredParameterLabels = {0, 1})
    public void export(PluginContext context, LocalProcessModelRanking lpms, File file) throws IOException {
        LPMsExport.exportLocalProcessModelRanking(lpms, file);
    }
}
